"""Generate packaging/version_info.txt from seqrename.__version__.

The version lives in exactly one place - src/seqrename/__init__.py - and the
Windows file-version resource is derived from it at build time.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from seqrename import __version__  # noqa: E402

OUT = Path(__file__).resolve().parent / "version_info.txt"

TEMPLATE = """# UTF-8
# Generated by packaging/make_version_info.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'SeqRename'),
        StringStruct('FileDescription', 'SeqRename - VFX sequence renamer'),
        StringStruct('FileVersion', '{version}.0'),
        StringStruct('InternalName', 'SeqRename'),
        StringStruct('OriginalFilename', 'SeqRename.exe'),
        StringStruct('ProductName', 'SeqRename'),
        StringStruct('ProductVersion', '{version}.0'),
      ]),
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def main() -> int:
    parts = __version__.split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        print(f"__version__ must be MAJOR.MINOR.PATCH, got {__version__!r}", file=sys.stderr)
        return 1
    major, minor, patch = (int(p) for p in parts)
    OUT.write_text(
        TEMPLATE.format(major=major, minor=minor, patch=patch, version=__version__),
        encoding="utf-8",
    )
    print(f"Wrote {OUT} for version {__version__}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
