# PyInstaller spec - onedir build of the SeqRename GUI.
# Run from the repo root on Windows:  pyinstaller packaging\SeqRename.spec
from pathlib import Path

ROOT = Path(SPECPATH).parent
SRC = ROOT / "src"

# Generated by packaging/make_version_info.py; build.ps1 refreshes it first.
VERSION_INFO = ROOT / "packaging" / "version_info.txt"

a = Analysis(
    # entry.py, not gui/__main__.py: the frozen entry script runs without a
    # parent package, so it must use absolute imports.
    [str(ROOT / "packaging" / "entry.py")],
    pathex=[str(SRC)],
    binaries=[],
    datas=[(str(SRC / "seqrename" / "gui" / "assets"), "seqrename/gui/assets")],
    hiddenimports=["seqrename.gui.app"],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        # Qt modules the app never touches - keeps the folder around 100 MB.
        "PySide6.QtQml", "PySide6.QtQuick", "PySide6.QtQuick3D", "PySide6.QtQuickWidgets",
        "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets", "PySide6.QtWebChannel",
        "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets", "PySide6.Qt3DCore",
        "PySide6.Qt3DRender", "PySide6.QtCharts", "PySide6.QtDataVisualization",
        "PySide6.QtBluetooth", "PySide6.QtNetworkAuth", "PySide6.QtPositioning",
        "PySide6.QtSensors", "PySide6.QtSerialPort", "PySide6.QtSql", "PySide6.QtTest",
        "PySide6.QtOpenGL", "PySide6.QtOpenGLWidgets", "PySide6.QtPdf", "PySide6.QtPdfWidgets",
        "tkinter", "unittest", "pydoc_data",
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="SeqRename",
    debug=False,
    strip=False,
    upx=False,
    console=False,               # windowed app - no console flash
    icon=str(ROOT / "packaging" / "seqrename.ico"),
    version=str(VERSION_INFO) if VERSION_INFO.exists() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="SeqRename",
)
